export const hachiConfig = {
  enabled: true,
  renderer: 'sprite',
  defaultState: 'idle',
  enableAutonomousMovement: false,
  enableCursorReactions: true,
  enableSectionInteractions: false,
  enableSpeech: true,
  enableAssistant: true,
  enableSounds: true,
  maxAutonomousActionsPerMinute: 4,
  desktopScale: 1,
  mobileScale: 0.72,
  walkingSpeed: 90,
  runningSpeed: 170,
  autonomousDelayRangeMs: [11000, 22000],
  movementPadding: 18,
  debug: import.meta.env.DEV && new URLSearchParams(window.location.search).has('hachi-debug'),
  assistantName: 'Hachi',
  subtitle: "Furfoo's AI Helper",
  statusLabel: 'Here to help',
  // Replace these temporary assets with the final Hachi 3D model, transparent video,
  // Lottie animation, or PNG. Every visual state is controlled here only.
  assets: {
    hidden: '/media/brand/hachi-3d.png',
    entering: '/media/brand/hachi-action.png',
    idle: '/media/brand/hachi-3d.png',
    looking: '/media/brand/hachi-portrait.png',
    blinking: '/media/brand/hachi-portrait.png',
    sniffing: '/media/brand/hachi-3d.png',
    walking: '/media/brand/hachi-3d.png',
    running: '/media/brand/hachi-action.png',
    sitting: '/media/brand/hachi-3d.png',
    lying: '/media/brand/hachi-portrait.png',
    waking: '/media/brand/hachi-portrait.png',
    stretching: '/media/brand/hachi-action.png',
    tailWagging: '/media/brand/hachi-action.png',
    headTilting: '/media/brand/hachi-portrait.png',
    peeking: '/media/brand/hachi-portrait.png',
    jumping: '/media/brand/hachi-action.png',
    startled: '/media/brand/hachi-action.png',
    excited: '/media/brand/hachi-action.png',
    speaking: '/media/brand/hachi-portrait.png',
    listening: '/media/brand/hachi-portrait.png',
    guiding: '/media/brand/hachi-action.png',
    recommending: '/media/brand/hachi-action.png',
    celebrating: '/media/brand/hachi-action.png',
    returningHome: '/media/brand/hachi-3d.png',
    hovered: '/media/brand/hachi-3d.png',
    open: '/media/brand/hachi-3d.png',
    wave: '/media/brand/hachi-3d.png',
    thinking: '/media/brand/hachi-3d.png',
    success: '/media/brand/hachi-action.png',
    error: '/media/brand/hachi-portrait.png',
    minimized: '/media/brand/hachi-3d.png',
    sleeping: '/media/brand/hachi-portrait.png',
    fallback: '/media/brand/hachi-3d.png',
  },
  brand: { red: '#EF290F', cream: '#FFF9ED', ink: '#34251F' },
  soundFile: '/sounds/duck-squeak.mp3',
  barkSoundFile: '/sounds/hachi-bark.mp3',
  barkStartOffset: 0.14,
  soundEnabledByDefault: true,
  whatsappNumber: '601XXXXXXXX', // TODO: Confirm with Furfoo
  defaultWhatsappMessage: 'Hi Furfoo, I was speaking with Hachi and need some assistance.',
  welcome: {
    greeting: "Hi! I'm Hachi, Furfoo's little helper 🐾",
    cleanGreeting: "Hi! I'm Hachi 🐾",
    detail: 'You can move me anywhere. I know Furfoo’s catalogue and can explain every product match.',
  },
  healthDisclaimer: 'Hachi provides general product guidance only. For ongoing, severe, or urgent health concerns, please consult a veterinarian.',
  urgentResponse: 'This may need professional veterinary attention. Please contact a veterinarian or emergency veterinary clinic as soon as possible.',
  enableExitPrompt: true,
  enableProactivePrompts: false,
  enableFreeTextInput: true,
  enableAdoptionFlow: true,
  maxProactivePromptsPerSession: 2,
  proactivePromptGapMs: 40000,
  sleepAfterMs: 60000,
  spriteSheet: '/hachi/hachi-expression-sheet.png',
  sectionInteractions: [
    { id: 'story', selector: '#story', state: 'sitting', anchor: 'bottom-left', message: 'Welcome to Furfoo. This is where all the good smells come from.', persistent: false },
    { id: 'products', selector: '#products', state: 'sniffing', anchor: 'bottom-right', message: 'Should Hachi help you pick one?', action: 'menu' },
    { id: 'treats', selector: '#treat-shelf', state: 'excited', anchor: 'bottom-left', message: 'Hachi was only checking the quality.', action: 'treat-intro' },
    { id: 'reviews', selector: '#reviews', state: 'tailWagging', anchor: 'bottom-right', message: 'Hachi likes this part.', persistent: false },
    { id: 'adoption', selector: '#adoption', state: 'sitting', anchor: 'bottom-left', message: "Some of Hachi's friends are looking for a loving home.", action: 'adoption' },
    { id: 'faq', selector: '#faq', state: 'headTilting', anchor: 'bottom-right', message: 'Got a question? Hachi can help.', action: 'faq' },
    { id: 'footer', selector: 'footer', state: 'sleeping', anchor: 'bottom-right', message: 'Still here if you need me.', persistent: false },
  ],
  proactivePrompts: [
    { id: 'products', selector: '#products', message: 'Need help choosing one?', action: 'bath-intro' },
    { id: 'treats', selector: '#treat-shelf', message: 'Want Hachi to pick a treat?', action: 'treat-intro' },
    { id: 'adoption', selector: '#adoption', message: "Some of Hachi's friends are looking for homes.", action: 'adoption' },
  ],
}
